### ISSUE TITLE
Suggestion - using OpenDalle/DPO model as default

### ISSUE THREAD

**Issue by C00reNUT** [YangLing0818/RPG-DiffusionMaster#19]
Hello, 
thank you for your work and making it public, it's a very nice idea. 

I just wanted to suggest you to use OpenDalle https://civitai.com/models/238116?modelVersionId=275681 or other DPO finetuned mdoel https://civitai.com/models/239836?modelVersionId=270839 

In my experiments OpenDalle is better. I follows prompt better than regular SD XL models.

**Comment by YangLing0818** [comment]
> Hello, thank you for your work and making it public, it's a very nice idea.
> 
> I just wanted to suggest you to use OpenDalle https://civitai.com/models/238116?modelVersionId=275681 or other DPO finetuned mdoel https://civitai.com/models/239836?modelVersionId=270839
> 
> In my experiments OpenDalle is better. I follows prompt better than regular SD XL models.

Thanks for your constructive suggestions. We will consider to try these models in next update.
