### ISSUE TITLE
Style database not found: styles.csv

### ISSUE THREAD

**Issue by RahulSinghalChicago** [YangLing0818/RPG-DiffusionMaster#20]
Anyone know which styles.csv this should be?

**Comment by ShashwatNigam99** [comment]
The code in this repository is taken from https://github.com/hako-mikan/sd-webui-regional-prompter. You can find the file here. It is not required though.

**Comment by YangLing0818** [comment]
> Anyone know which styles.csv this should be?

You can run our code without this file. Currently, we focus on optimizing the whole pipeline of our MLLM-controlled framework, so we overlook to optimize these plugins. We will fix it in next version. Thanks for your interest!

**Comment by RahulSinghalChicago** [comment]
The file `styles.csv` is available at this link https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/10129

**Comment by RahulSinghalChicago** [comment]
> The code in this repository is taken from https://github.com/hako-mikan/sd-webui-regional-prompter. You can find the file here. It is not required though.

`style.css` is available, but unfortunately not the `styles.csv` found it here https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/10129
