### ISSUE TITLE
WebUI extension is ready

### ISSUE THREAD

**Issue by zydxt** [YangLing0818/RPG-DiffusionMaster#28]
Hey folks, I created  an extension [sd-webui-rpg-diffusionmaster](https://github.com/zydxt/sd-webui-rpg-diffusionmaster)
I added Gemini Pro and OpenAI Azure support but the local LLM support is still on the way. 
Hope this can help you playing with RPG-DiffusionMaster

The extension's code structure was quite different and I'm not sure if I should try to merge it into this repo. Let me know if you have any suggestion

**Comment by YangLing0818** [comment]
good try!
