### ISSUE TITLE
Separate LLM part to be an A1111 extension

### ISSUE THREAD

**Issue by continue-revolution** [YangLing0818/RPG-DiffusionMaster#3]
It seems that the majority part of this project is copied from AUTOMATIC1111 Stable Diffusion WebUI. This is absolutely a good thing. But to make things easier I would highly suggest you to separate your llm part to be an extension, so that everyone can enjoy your work without any difficulty.

**Comment by YangLing0818** [comment]
Thanks for your valuable suggestions, we will try to do that and welcome collaborators

**Comment by zydxt** [comment]
Hi, I created an extension [here](https://github.com/zydxt/sd-webui-rpg-diffusionmaster)
It basically separates the LLM part and controls the UI components of [sd-webui-regional-prompter](https://github.com/hako-mikan/sd-webui-regional-prompter). Hope this will help
