### ISSUE TITLE
Success rate of the MLLM layout output (Colab notebook + example outputs)

### ISSUE THREAD

**Issue by ShashwatNigam99** [YangLing0818/RPG-DiffusionMaster#5]
Hello authors, thanks for this interesting work and for releasing the code.

I have setup a [colab notebook (GPT4)](https://colab.research.google.com/drive/1cGdfpqP8NYHWfPcwgAs3_Rq2l3MuUttM?usp=sharing) here, where I have been trying out some examples.

I wanted to discuss the frequent case where the MLLM doesn't output a layout that makes sense/ gives incorrect captions to different regions of the layout it outputs. In a few runs with a simple prompt -
`"A couple, the beautiful girl on the right, silver hair, braided ponytail, happy, dynamic, energetic, peaceful, the handsome young man on the right detailed gorgeous face, grin, blonde hair, enchanting"`
I got the outputs attached below (only one of them makes sense). I wanted to ask if this is expected or if there is a solution to this? Kindly let me know if I am not running the code in the intended way.
Here is a doc with the [expanded output](https://docs.google.com/document/d/1q5Dn4KlGr99uOsEbvA8BjyBan0LO7GMl3RhY3F2F0Xs/edit?usp=sharing) (1 success case, 1 failure case).

![gpt4_image_20240124_001743](https://github.com/YangLing0818/RPG-DiffusionMaster/assets/30972206/bada239a-0563-4458-93fa-e0ba2d2c4b4d)
![gpt4_image_20240124_050308](https://github.com/YangLing0818/RPG-DiffusionMaster/assets/30972206/4b50bf86-42ad-4bb9-9944-b780a45b2f6c)
![gpt4_image_20240124_051546](https://github.com/YangLing0818/RPG-DiffusionMaster/assets/30972206/a1c43e4a-ac8f-4950-a6ab-9beccd75dc4d)

**Comment by YangLing0818** [comment]
We think the main problem may be your ambiguous text prompt because the girl and the man are **both on the right**. Another reason is you may neglect to set the variable "use_base", and such setting is critical for **generating different objects of the same class**, which has been well discussed in the ablation study of our paper.

**Comment by ShashwatNigam99** [comment]
Hi @YangLing0818 thanks for the reply!
I realize the text is ambiguous, it is one of the example prompts in your README - you might want to update that!

Also, I have been using the base prompt option with a weight of 0.2 (standard regional prompter settings). Thanks for the pointer.
