### ISSUE TITLE
generation object outside of the region

### ISSUE THREAD

**Issue by X-fxx** [YangLing0818/RPG-DiffusionMaster#54]
![image](https://github.com/YangLing0818/RPG-DiffusionMaster/assets/113758018/79734903-66f3-4a1a-a65b-d2862efddc66)

Why does this person's avatar appear in the moon area? Which part of the method in the text does it correspond to?

**Comment by YangLing0818** [comment]
Thanks for your comment. Our region planning is only designed for providing proper initial position and size. Hence, in the denoising process, we enable model to adaptively modificate the size of objects for better generation quality.
